// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDjJFBvOClSS9imP9mhb8hDCQ4iLkyJDu8",
      authDomain: "medoment-tea-serve.firebaseapp.com",
      projectId: "medoment-tea-serve",
      storageBucket: "medoment-tea-serve.firebasestorage.app",
      messagingSenderId: "47791069713",
      appId: "1:47791069713:web:81e6fafe094631aae26fb0");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyDjJFBvOClSS9imP9mhb8hDCQ4iLkyJDu8",
      authDomain: "medoment-tea-serve.firebaseapp.com",
      projectId: "medoment-tea-serve",
      storageBucket: "medoment-tea-serve.firebasestorage.app",
      messagingSenderId: "47791069713",
      appId: "1:47791069713:web:81e6fafe094631aae26fb0");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJFBvOClSS9imP9mhb8hDCQ4iLkyJDu8',
    appId: '1:47791069713:ios:66143272ad765a48e26fb0',
    messagingSenderId: '47791069713',
    projectId: 'medoment-tea-serve',
    storageBucket: 'medoment-tea-serve.firebasestorage.app',
    iosBundleId: 'com.example.teaServe',
  );
}
