// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmyWy3YhmiV2rZE-aXOezt-mWfQt49PU',
    appId: '1:1009124765268:web:beebe0d88efb24edec47c1',
    messagingSenderId: '1009124765268',
    projectId: 'internal-ht',
    authDomain: 'internal-ht.firebaseapp.com',
    storageBucket: 'internal-ht.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5NSn6y2rAhzJNjqtf6L3JwWsIhVfzng',
    appId: '1:1009124765268:android:a9b3a99317aa3c58ec47c1',
    messagingSenderId: '1009124765268',
    projectId: 'internal-ht',
    storageBucket: 'internal-ht.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAyvLAk2d-i1d8d-yoXv23WsVCdxRgFg',
    appId: '1:1009124765268:ios:66143272ad765a48ec47c1',
    messagingSenderId: '1009124765268',
    projectId: 'internal-ht',
    storageBucket: 'internal-ht.firebasestorage.app',
    iosBundleId: 'com.example.teaServe',
  );

}