name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'  # Specify your Flutter version
          channel: 'stable'
          cache: true
      
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
      
      # Build web app
      - name: Build web app
        run: flutter build web --release
      
      # Deploy to Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: internal-ht  # Replace with your Firebase project ID
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
